cmake_minimum_required(VERSION 4.2)
project(SVM)
set(CMAKE_CXX_STANDARD     20)
set(CMAKE_CXX_STANDARD_REQUIRED YES)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(SVM_lib STATIC core/src/SVC.cpp core/src/Kernel.cpp)
target_include_directories(SVM_lib PUBLIC core/include)
enable_testing()
add_subdirectory(tests)
