name: build and test

on:
  push:
      branches: [ svr_dev]
  pull_request:
      branches: [ svr_dev]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install CMake & CTest
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        working-directory: ./build
        run: ctest 